### ISSUE TITLE
I install wix. But the error still exist.

### ISSUE THREAD

**Issue by wjtGitHub** [felixrieseberg/electron-wix-msi#11]
![image](https://user-images.githubusercontent.com/17404628/39531562-ffa1422c-4e5d-11e8-843f-6c9100cd38ab.png)
![image](https://user-images.githubusercontent.com/17404628/39531574-06cae620-4e5e-11e8-9540-7168e962b3cf.png)
# how to solve it.

**Comment by wjtGitHub** [comment]
@felixrieseberg

**Comment by codebude** [comment]
Hi @wjtGitHub ,

this is because the WIX installer doesn't add itself to the system %path%-variable. So add the WIX "bin"-directory (should be: `C:\Program Files (x86)\WiX Toolset v3.11\bin`) [to the system path](https://superuser.com/a/949577/161102), restart the console/shell you're working in and try it again.

**Comment by wjtGitHub** [comment]
@codebude thank you very much.
